name: Terraform Destroy

on:
  workflow_dispatch: # This makes the workflow trigger manually
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-east-1'
      approval_required: # Optional input for approval
        description: 'Require approval before apply (true/false)'
        type: boolean
        default: false

jobs:
  approval:
    name: Approval
    if: github.event.inputs.approval_required == true
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval Check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.reviewPendingDeploymentsForRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.run.id,
            environment_ids: [github.event.inputs.environment_id],
            state: 'pending',
            })
            core.setFailed('Approval required. Please review the plan and approve.');

  deploy:
    runs-on: ubuntu-latest
    needs: [approval]
    if: always() && (needs.approval.result == 'success' || github.event.inputs.approval_required != true)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
            aws-region: ${{ github.event.inputs.region}}

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionSession
          aws-region: ${{ github.event.inputs.region}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Destroy
        run: terraform destroy