apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-pvc
  namespace: asiayo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    volumeName: service-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-pv
  namespace: asiayo
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/service-volume
  persistentVolumeReclaimPolicy: Recycle
